language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jorge/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true jorge/frontend npm test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "test_terminal"
  env: "docker-test-terminal"
  bucket_name: "elasticbeanstalk-us-west-2-513893146427"
  bucket_path: "test_terminal"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
