FROM node:16-alpine
#Assign user node
USER node
#create directory 
RUN mkdir -p /home/node/app
#Assign working directory
WORKDIR /home/node/app
#Copy package.json and change permisions
COPY --chown=node:node ./package.json ./
#Run command npm install
RUN npm install
#Copy all directories and change permisions
COPY --chown=node:node ./ ./
#Run command npm npm start 
CMD ["npm", "start"]